using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TmsApi.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddLearningRecords : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "UserId",
                table: "Students",
                type: "text",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "AttendanceRecords",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    StudentId = table.Column<int>(type: "integer", nullable: false),
                    CourseId = table.Column<int>(type: "integer", nullable: false),
                    Date = table.Column<DateOnly>(type: "date", nullable: false),
                    Status = table.Column<int>(type: "integer", nullable: false),
                    Remarks = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AttendanceRecords", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AttendanceRecords_Courses_CourseId",
                        column: x => x.CourseId,
                        principalTable: "Courses",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_AttendanceRecords_Students_StudentId",
                        column: x => x.StudentId,
                        principalTable: "Students",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Grades",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    AssessmentId = table.Column<int>(type: "integer", nullable: false),
                    StudentId = table.Column<int>(type: "integer", nullable: false),
                    Score = table.Column<decimal>(type: "numeric(5,2)", nullable: false),
                    Remarks = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    GradedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    GradedBy = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Grades", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Grades_Assessments_AssessmentId",
                        column: x => x.AssessmentId,
                        principalTable: "Assessments",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Grades_Students_StudentId",
                        column: x => x.StudentId,
                        principalTable: "Students",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            // Notifications may have been created by an earlier development build
            // before this migration was recorded. Reconcile that table in place so
            // migration recovery never destroys existing notification data.
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Notifications" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    "UserId" character varying(450) NOT NULL,
                    "Title" character varying(200) NOT NULL,
                    "Message" character varying(2000) NOT NULL,
                    "Type" text NOT NULL,
                    "IsRead" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
                );
                ALTER TABLE "Notifications" ADD COLUMN IF NOT EXISTS "UserId" character varying(450);
                ALTER TABLE "Notifications" ADD COLUMN IF NOT EXISTS "Title" character varying(200);
                ALTER TABLE "Notifications" ADD COLUMN IF NOT EXISTS "Message" character varying(2000);
                ALTER TABLE "Notifications" ADD COLUMN IF NOT EXISTS "Type" text;
                ALTER TABLE "Notifications" ADD COLUMN IF NOT EXISTS "IsRead" boolean;
                ALTER TABLE "Notifications" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamp with time zone;
                """);

            migrationBuilder.CreateIndex(
                name: "IX_AttendanceRecords_CourseId",
                table: "AttendanceRecords",
                column: "CourseId");

            migrationBuilder.CreateIndex(
                name: "IX_AttendanceRecords_StudentId_CourseId_Date",
                table: "AttendanceRecords",
                columns: new[] { "StudentId", "CourseId", "Date" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Grades_AssessmentId_StudentId",
                table: "Grades",
                columns: new[] { "AssessmentId", "StudentId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Grades_StudentId",
                table: "Grades",
                column: "StudentId");

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_Notifications_UserId_IsRead_CreatedAt"
                ON "Notifications" ("UserId", "IsRead", "CreatedAt");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AttendanceRecords");

            migrationBuilder.DropTable(
                name: "Grades");

            migrationBuilder.DropTable(
                name: "Notifications");

            migrationBuilder.DropColumn(
                name: "UserId",
                table: "Students");
        }
    }
}
